### PR TITLE
ci: add test & coverage build for MacOS and Windows

### PR DESCRIPTION
**Pull request by mydiemho**
also update badge to point to newer pipeline (has better integration
with GitHub Check)

### CODE REVIEW

**Comment by elizabethhalper** [comment]
Is it testing for any specific % for coverage, or just adding the check?

**Comment by mydiemho** [comment]
> Is it testing for any specific % for coverage, or just adding the check?

it's adding tests to run on Windows & MacOS.  and also switching to the newer pipeline (created with the newer YAML wizard on ADO)

**Comment by elizabethhalper** [comment]
> > Is it testing for any specific % for coverage, or just adding the check?
> 
> it's adding tests to run on Windows & MacOS. and also switching to the newer pipeline (created with the newer YAML wizard on ADO)

Okay so no minimum coverage is set yet?

**Comment by mydiemho** [comment]
> Okay so no minimum coverage is set yet?

Minimum coverage already exist.  It's at 60% right now

https://github.com/Microsoft/vott-react/blob/master/codecov.yml

**Pull request merged**
